### ISSUE TITLE
Fix euclidean distance on absolute value for MathHelper.equal

### ISSUE THREAD

**Issue by litneet64** [DD2480-Group-22/assignment-1#100]
Function `MathHelper.equal` returns difference between double `a` and `b` without absolute value and compares it with an epsilon, making it return `true` even when distances are dismal between each value if `b` is large enough.

**Comment by ErikRichardS** [comment]
I already fixed this.

**Comment by nilsstre** [comment]
Since #100 has been resolved, we can close this pull request.
