### ISSUE TITLE
Add statement of contributions to the README

### ISSUE THREAD

**Issue by nilsstre** [DD2480-Group-22/assignment-1#83]

**Comment by felipevicencion** [comment]
I did LIC functions 2, 5, 8, 9, 11 and 13.

**Comment by ErikRichardS** [comment]
I did LIC functions 0, 1, 3, 14. One test for the entire Decide function.

**Comment by litneet64** [comment]
I did functions 4, 10, 12 and their corresponding unit tests, helped with the Slack-Travis integration and helped fix some minor issues.
